### ISSUE TITLE
Issues after combing through analysis.py after merge.

### ISSUE THREAD

**Issue by thejevans** [thejevans/mla#10]
@jasonfan1997:
- `ThreeMLPsAnalysis` needs `produce_and_minimize()`.
- `ThreeMLPsAnalysis` should not build an event model internally. Remove `_init_event_model()`.
- `reduce` is a python keyword. Don't use it as a variable name in `ThreeMLEventModel`.
- `set_data()` in `ThreeMLPsAnalysis` should be handled entirely in `ThreeMLEventModel`.
- `calculate_ts` in `ThreeMLPsAnalysis` has a `float` return type hint, but returns a tuple. Either change the type hint or the return type.
- It looks like `ThreeMLPsAnalysis` should only accept event models of type `ThreeMLEventModel`. Change the type hints to reflect this.
- Lots of attributes in `ThreeMLPsAnalysis` are defined outside of `__init__()`. This should not happen.
- There are a lot of protected items in `ThreeMLEventModel` being accessed directly in `ThreeMLPsAnalysis`. Either access them another way or remove the "_" making them unprotected.
- Lines 532/533, 550/551: Don't `except` without a specific exception. Make sure to use "raise from" syntax (PEP-3134). Add "Raises: " lines in docstring.
- Line 637-640: The type hints are very long. Define a custom type hint for this at the top of the file.
- `preprocess_ts` should not have an optional return type in `ThreeMLPsAnalysis`. it should never return `none`.
- Docstrings for `ThreeMLPsAnalysis` need to be completed.

**Comment by jasonfan1997** [comment]
1. `ThreeMLPsAnalysis` actually got no produce_and_minimize() as the minimization is done in 3ML
2. Will removed. Old code during development.
3. OK
4. Notice the data here is different from what store in EventModel, here is the actual data used in TS calculation, while I think EventModel should only store things that are related to experiment and response function.
5. Will fix
6. Will fix.
7. Will fix.
8. I will remove the _. Old code again.
9. Will fix
10. Will fix
11. Will fix
12. Will fix

**Comment by thejevans** [comment]
1. It still needs to be there, even if it returns junk/none

4. We should probably meet about this so you can explain it to me
