### ISSUE TITLE
Issues after combing through injectors.py after merge.

### ISSUE THREAD

**Issue by thejevans** [thejevans/mla#11]
@jasonfan1997:
- Remove `inject_nsignal_events()` from both injectors. To have this functionality, instead add an optional parameter `n_signal_observed` to `inject_signal_events`.
- Remove `set_position()` in `TimeDependentPsInjector` these values can be directly changed by altering the source dict.
- `reduced_sim()`, `inject_background_events()`, and `inject_signal_events()` in `TimeDependentPsInjector` all need the same signature as in `PsInjector`
- No need for `inject_background_events_No_time()` in `TimeDependentPsInjector`. Please remove.
- There are multiple attributes in `TimeDependentPsInjector` defined outside of `__init__()`. This should not happen.
- `set_background_profile()` should instead be done using the `@property` decorator. The docstring for this should also have "Raises: " lines.
- `set_signal_profile()` should be removed.
- Does `inject_background_and_signal()` do anything that injecting them separately would not? If not, please remove. If so, please explain.
- Docstrings in `TimeDependentPsInjector` need to be completed

**Comment by jasonfan1997** [comment]
1. I would rather keep it separate, the only real meaning of inject_nsignal_events() is to do the ns bias tested that I am doing and in theory it can be removed later when we finish testing. Having that inject_signal_events both confuse user plus they shouldn't use it at all.

2. Will do that.
3.Will fix
4. Will do
5. Will fix
6. I don't think making it into property is a good idea. The background profile consists of something else besides the time_profile object. It basically adds much more complication to it.
7. Will do.
8. Will remove. Exist only for testing.
9. Will do

**Comment by jasonfan1997** [comment]
I rethink and I think we can merge the inject nsignal event as I probably want to keep it for unit tests (maybe?)
