### ISSUE TITLE
Issues after combing through models.py after merge.

### ISSUE THREAD

**Issue by thejevans** [thejevans/mla#12]
@jasonfan1997:
- Are we sure that line 266 does the right thing? Last I remember we hadn't settled on an answer.
- `__init__()` in `ThreeMLEventModel` needs to call `super().__init__()`.
- There is a lot of code duplication throughout `ThreeMLEventModel` that could be replaced with calls to `super().func_name()`.
- The exception in `get_energy_sob()` needs to have an exception type specified.
- `get_energy_sob()` is the same as `get_log_sob_gamma_splines()` in the super class. It should be renamed to match and have the same signature.
- `update_model()` and `update_position()` should be done using the `@property` decorator functions instead.
- Docstrings need to be completed for `ThreeMLEventModel`

**Comment by jasonfan1997** [comment]
1. I think my implementation is correct.
try
np.searchsorted(np.array([1,2,3,4,5,6,7]),2.5) and it will return 2 and it should land in the second bin is our histogram, meaning the index should be 1.

2. Will fix
3. I actually can't find a replaceable code. Most of the codes are actually doing some different things. 
4. Will fix
5. Actually they are different, plus get_energy_sob do not involve spline at all so I don't want to cause confusion
6. I think using update model and update position function is more intuitive to user.

**Comment by jasonfan1997** [comment]
I am thinking cut the inheritance since only the background dec spline is the same. Having them separate however can ensure I wouldn't need to change things in EventModel when some functionality in 3ML requires me to change something in models.

**Comment by thejevans** [comment]
1. I'll check on this more later
2.
3. There is a lot of code duplication, for sure. Even if it makes sense to break up the methods in the parent class, it's a good idea to remove the duplication. For instance, `_create_sob_ratio()` only has one line different as far as I can tell.
4.
5. I looked at the method signature and it was the same. It says it returns a spline as well. That's where the confusion here came from.
6. In python, getter and setter methods are the exception, not the rule, as opposed to languages like java. These are very clearly setter methods, and `@property` was made for things like this.

**Comment by jasonfan1997** [comment]
3. _create_sob_ratio in ThreeMLEventModel create the sob_ratio on the fly instead of doing the spline thing. I already decided to cut the inheritance as everything is kind of different except the background dec spline.

5. My bad. Forgot to change

6. For position, actually it is more like telling the model how to cut simulation to some dec band. I will actually change it completely. For model, I will make spectrum a property.
