### ISSUE TITLE
Extra arguments in dataclass

### ISSUE THREAD

**Issue by jasonfan1997** [thejevans/mla#18]
https://github.com/thejevans/mla/blob/4620b1b292dc6d26d02532bf2704738453546a4b/mla/core.py#L89

We need to init the preprocessor during minimize_ts like line 58.
However I am not sure what is the proper way to handle extra arguments in dataclass. I am trying to fix it but welcome any ideas. @thejevans

**Comment by thejevans** [comment]
The preprocessor needs to be created first, then added to the analysis object

**Comment by thejevans** [comment]
The goal is to have the analysis object be a static item once created so it can be shared across multiple processes

**Comment by thejevans** [comment]
looking at it now, I have to fix this in a few other places.

**Comment by jasonfan1997** [comment]
Creating the preprocessor requires the generated events which means it is impossible to do it under the current structure. If the goal is what you said then we have to refactor it again.

**Comment by thejevans** [comment]
yeah lemme work on this tonight

**Comment by thejevans** [comment]
alright, I pushed a fix along with some changes to generalize the minimizer
