### ISSUE TITLE
Fail when zero events

### ISSUE THREAD

**Issue by jasonfan1997** [thejevans/mla#20]
https://github.com/thejevans/mla/blob/d7dee4ffd114df7672bcf568b9e148929208ae92/mla/test_statistics.py#L77

It will throw error(I think) when you pass in zero event. Either catch that during minimize_ts and evaluate_ts(return zero when no event at the beginning ) or try to deal with it during _preprocess

**Comment by thejevans** [comment]
It will throw a warning for sure. where's the errror?

**Comment by thejevans** [comment]
looks like the error will come from the background_dec_spline in event_model.
is ts = 0 for no events the behavior that we want? If so, I'll add it.

**Comment by jasonfan1997** [comment]
I think a lot of places will throw an error if we pass zero events to it. Yes, we do need to return a ts of 0 for zero events since it is normal for a short time window having no background events.

**Comment by thejevans** [comment]
fix implemented
