### ISSUE TITLE
n_signal_observed

### ISSUE THREAD

**Issue by jasonfan1997** [thejevans/mla#21]
https://github.com/thejevans/mla/blob/d7dee4ffd114df7672bcf568b9e148929208ae92/mla/models.py#L522

I think we should keep the n_signal_observed and whether enable Poisson fluctuation on it as optional arguments. Even if it can't be pass directly from produce_and_minimize. Then I can just write my own produce_and_minimize and produce_trial to test ns_bias without altering the source code.

Also maybe allowing the user to pass in n_signal_observed or enable Poisson fluctuation on it is not a bad idea. A lot of the theory papers just gave you an expected number of neutrino instead of the spectrum itself(and also in the current version we can only inject powerlaw spectrum and hardcode in it while most of the theory paper got their own spectrum which has no closed-form).

**Comment by thejevans** [comment]
functionality added
