### ISSUE TITLE
Should we make default sampling width?

### ISSUE THREAD

**Issue by jasonfan1997** [thejevans/mla#25]
https://github.com/thejevans/mla/blob/9ff3db3562d605485b293aa9e1ab2abffd419e8c/mla/models.py#L169

I think for any point source analysis it wouldn't make sense to not setting a sampling width. Maybe 3 degrees?

**Comment by thejevans** [comment]
I guess if that's true, we should pick a value that will be big enough for the vast majority of analyses. is 3 good enough? If so, sure.

**Comment by thejevans** [comment]
@mjlarson confirmed that 3 is good. Change made.
