### ISSUE TITLE
prepro.bounds?

### ISSUE THREAD

**Issue by jasonfan1997** [thejevans/mla#26]
https://github.com/thejevans/mla/blob/e01902c640d5dc7fe44d76380a6558d7c56d8fa5/mla/analysis.py#L60

I can't find the place where the prepro.bounds are defined? How should the user pass in bound into the function and how can we set default bounds?

**Comment by thejevans** [comment]
I tweaked the implementation a bit to fix a bug and make it more clear in the `new_ts` branch

I don't think it needs to be passed through the ts_preprocessor, so I just let the user send it directly to the `minimize_ts()` function.
