### ISSUE TITLE
ns_bias in fitting

### ISSUE THREAD

**Issue by thejevans** [thejevans/mla#51]
There is an ns bias in fitting that exists:
1. whether or not we use the newton method or let the minimizer fit ns
2. even if we remove both the time and energy factors from the signal over background calculation
3. that is proportional to the length of the time window or number of background events

It's likely that this then due to the spatial signal over background factor.

**Comment by mjlarson** [comment]
If it's the spatial terms, that's really odd. Neither should have been changed in a long time now, but it's possible that there was some unintentional change that happened somewhere along the way.

Keep in mind that getting the ns ratio wrong (by fitting it incorrectly - which you've tested - or by having the wrong prepro.n_events) could also do something like this. It may be worth running through the n_events calculations just to double check, if the spatial calculations don't pan out.
