### ISSUE TITLE
Overwriting sob

### ISSUE THREAD

**Issue by jasonfan1997** [thejevans/mla#6]
https://github.com/thejevans/mla/blob/53c503daec0aaefa634a23e1c4f0f982d82fc86e/mla/analysis.py#L126

I think it will go wrong when doing the minimization step but I am not sure why.
I did something like 

        splines, sob = preprocessing
        sob_new = sob*np.exp([spline(gamma) for spline in splines])
        
        return np.log((ns/n_events*(sob_new - 1)) + 1)

**Comment by thejevans** [comment]
you saw this not working?

**Comment by thejevans** [comment]
This has confirmed to be an issue. Your fix is good.
