### ISSUE TITLE
Wrong likelihood formula

### ISSUE THREAD

**Issue by jasonfan1997** [thejevans/mla#7]
https://github.com/thejevans/mla/blob/53c503daec0aaefa634a23e1c4f0f982d82fc86e/mla/analysis.py#L158

drop actually accounts for events having zero spatial llh. If you want to use it, you can filter out all events with zero spatial pdf in evaluate_ts (Notice that you need to pass the total number of events before the filter. ) . Another solution is to forget the drop at all and just do -2*(np.sum(llhs)). it will not add a lot of CPU time since you already precompute the spatial pdf, but you will still need to compute the energy llh for those useless events. The first one got a more complicated formula but it is faster. Let me know which one you prefer.

**Comment by thejevans** [comment]
I think if dropping the events is faster, we should do it, but put an inline comment explaining its purpose

**Comment by jasonfan1997** [comment]
Will do
