### ISSUE TITLE
Time profiles have duplicate range and window properties 

### ISSUE THREAD

**Issue by thejevans** [thejevans/mla#8]
We should get rid of the `get_range()` function and settle on a property either named `window` or `range` that is of type `Tuple[Optional[float], Optional[float]]`.

**Comment by jasonfan1997** [comment]
let's call it range. I will get rid of get_range() function and remove the window

**Comment by thejevans** [comment]
in python, there is the `@property` decorator that handles getters/setters and protected variables. We should use that.
